name: Run Tests (SmartBox API)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Copy .env.example to .env (if needed)
        run: |
          if [ -f ".env.example" ]; then cp .env.example .env; fi

      - name: Build Docker containers
        run: docker-compose build

      - name: Run tests inside container
        run: docker-compose run --rm backend npm test

      - name: Shut down Docker containers
        run: docker-compose down